services:
  app:
    image: richarvey/nginx-php-fpm:39a8a77b
    user: 1000:1000
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/html
      - ./opt/conf/:/var/www/html/conf/
  # nginx:
  #   image: nginx:stable-alpine3.20-perl
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./app:/var/www/html
  #   depends_on:
  #     - php
  # php:
  #   image: php:8.3-fpm-alpine
  #   volumes:
  #     - ./app:/var/www/html

  # find . -depth -name "*.css?*" -exec sh -c 'f="{}"; mv -- "$f" "${f%.css?*}.css"' \;                    
  # find . -depth -name "*.svg?*" -exec sh -c 'f="{}"; mv -- "$f" "${f%.svg?*}.svg"' \;
